### PR TITLE
only support ruby 2.0+

### PR DESCRIPTION
**Pull request by kbaum**

### CODE REVIEW

**Comment by kbaum** [comment]
I'm going to go ahead and pull this in.

@danmayer - let me know if you need me to change anything. 

I bumped up the gem version too.  I don't have rights to release a new one.

thx!

**Comment by danmayer** [comment]
OK I released a gem update after pulling everything down send me your email and I will add you as a gem owner so you can publish the gem as well. Thanks for all the work on this, it is looking great.

**Comment by danmayer** [comment]
added you as an owner

**Comment by kbaum** [comment]
Great.  Thx!

**Pull request merged**
