### PR TITLE
Trace point for ruby 2 plus

### PR DESCRIPTION
**Pull request by kbaum**
Using TracePoint for ruby >= 2 gives a massive speed improvement.

Before:

```
                      user     system      total        real
coverband         6.110000   0.050000   6.160000 (  6.171213)
no coverband      0.170000   0.000000   0.170000 (  0.171993)
```

After:

```
                      user     system      total        real
coverband         0.840000   0.010000   0.850000 (  0.852229)
no coverband      0.160000   0.000000   0.160000 (  0.168215)
```

### CODE REVIEW

**Comment by kbaum** [comment]
@danmayer - the builds seemed to be sporadically failing due to a bundler problem but i'm not sure what's happening:

image

**Comment by kbaum** [comment]
@danmayer - fixed travis build failure.

**Comment by danmayer** [comment]
Nice, yeah it would be kind of nice to keep Ruby 1.9 support but really tracepoint is getting much better and to get this project fully where we would want it it is likely best to just drop support. I think might be good to just add a note in the readme that version X is the last version that will support Ruby 1.9

**Comment by kbaum** [comment]
Definitely agree. I think we should also note that the latest doesn't need
or use the c extension at this point.

**Comment by danmayer** [comment]
Agreed, should cleanup the docs, perhaps we do a major version bump on the next gem release to signify dropping support and making some significant changes / not requiring the c_extension.

**Comment by kbaum** [comment]
Sounds like a plan!

**Pull request merged**
