### PR TITLE
Avoid calling coverage with the same type twice on get_coverage_report

### PR DESCRIPTION
**Pull request by mtsmfm**
Currently, `get_coverage_report` calls `coverage` for the same type twice.
This PR makes `Coverband.configuration.store.get_coverage_report` two times faster.

## Script

```ruby
require 'bundler/setup'
require 'coverband'
require "./test/unique_files"
require 'benchmark'

4000.times { |index| require_unique_file("big_dog.rb.erb", dog_number: index) }
# warmup
3.times { Coverband.report_coverage }
dogs = 400.times.map { |index| Object.const_get("Dog#{index}") }
dogs.each(&:bark)

N = 10

Benchmark.bm do |x|
  x.report do
    N.times do
      Coverband.configuration.store.get_coverage_report
    end
  end
end
```

### Before

```
$ ruby foo.rb
D, [2021-12-27T13:31:27.354358 #5788] DEBUG -- : using default configuration
       user     system      total        real
   2.040388   0.128909   2.169297 (  2.181851)
```

### After

```
$ ruby foo.rb
D, [2021-12-27T13:30:26.371700 #5292] DEBUG -- : using default configuration
       user     system      total        real
   1.077262   0.129121   1.206383 (  1.213189)
```

### CODE REVIEW

**Comment by danmayer** [comment]
Thanks, @mtsmfm I can get this in for the next release. With the new release of Rails and Ruby, I need to update the CI configs and get things set up for the newest releases.

We don't typically spend a lot of time or benchmarking the reporting as it is used from time to time, we try to spend most efforts ensuring data collection is as low of impact in terms of memory/CPU overhead. 

Are you working on a project where you are seeing the reporting views as very slow? If so totally awesome to speed them up, even in large projects I haven't typically seen it slow down to much.

**Review by danmayer — APPROVED** [review]
will merge when I fix CI for Ruby/Rails updates

**Comment by mtsmfm** [comment]
> Are you working on a project where you are seeing the reporting views as very slow?

Yes.
Our project has 3000+ files and Coverband with hash store spends about 20+ seconds to respond index page.
You can reproduce this slow index page problem with the following patch and script:

```diff
diff --git a/test/big_dog.rb.erb b/test/big_dog.rb.erb
index eb3ea08..f7fd0aa 100644
--- a/test/big_dog.rb.erb
+++ b/test/big_dog.rb.erb
@@ -9,4 +9,10 @@ class Dog<%=dog_number%>
   def bark
     'woof'
   end
+
+  <% 50.times do |i| %>
+    def bark<%=i%>
+      'woof'
+    end
+  <% end %>
 end
```

```ruby
require 'bundler/setup'
require 'coverband'
require 'benchmark'
require 'active_support/all'
require 'ruby-prof'
require 'pry-byebug'

Coverband.configuration.store.clear!

require "./test/unique_files"

3000.times { |index| require_unique_file("big_dog.rb.erb", dog_number: index) }
dogs = 3000.times.map { |index| Object.const_get("Dog#{index}") }
dogs.each(&:bark)

Coverband.report_coverage

Benchmark.bm do |x|
  x.report do
    Coverband::Reporters::Web.new.call({'rack.input' => ''})
  end
end

__END__
$ COVERBAND_HASH_REDIS_STORE=1 ruby foo.rb
/workspace/coverband/lib/coverband.rb:27: warning: already initialized constant Coverband::Adapters::RedisStore
/workspace/coverband/lib/coverband/adapters/redis_store.rb:13: warning: previous definition of RedisStore was here
D, [2021-12-28T02:35:11.036625 #9338] DEBUG -- : using default configuration
       user     system      total        real
  25.621329   0.197376  25.818705 ( 25.820793)
```

I think big_dog.rb.erb is too small to use in benchmark.

**Comment by danmayer** [comment]
@mtsmfm this is in `gem 'coverband', '= 5.2.0.rc.1'` if you want to help test the RC

**Pull request merged**
