### PR TITLE
Redis improvements

### PR DESCRIPTION
**Pull request by oded-zahavi**

### CODE REVIEW

**Comment by danmayer** [comment]
I will revisit this once I get the Alpha branch out.

**Comment by oded-zahavi** [comment]
Hey thanks for sure we can keep these pull requests on hold for now once you merge your alpha branch to master I'll rebase and submit my pull requests on top of that. Thanks.

**Comment by danmayer** [comment]
ok, @oded-zahavi this was a bit complicated to pull out from the other changes, but not too bad... I couldn't take the PR directly, but I cherry-picked over some of the changes and cleaned it up to resolve the various conflicts... I credited you and this PR in the commit.

Thanks for the features and the support. Nice to have the namespace support. https://github.com/danmayer/coverband/commit/52ef943a36caaa0fb4fbb5c60a8aba8b4de31b6a

**Comment by danmayer** [comment]
this is in the 2.0.1 release https://github.com/danmayer/coverband/blob/master/changes.md#201

**Pull request closed without merging**
