### PR TITLE
Inlining add file within trace point

### PR DESCRIPTION
**Pull request by kbaum**
This is a strange one but inlining the code within the TracePoint of the line gives a noticeable performance boost.

Before:

```ruby
                      user     system      total        real
coverband         0.750000   0.010000   0.760000 (  0.775195)
no coverband      0.180000   0.000000   0.180000 (  0.174714)
```

After:

```ruby
                      user     system      total        real
coverband         0.700000   0.010000   0.710000 (  0.718418)
no coverband      0.190000   0.000000   0.190000 (  0.185560)
```

### CODE REVIEW

**Comment by danmayer** [comment]
looks good but need to fix the failing specs checking for add_file.... So I think a lot of the other PRs aren't needed as they built on top of each other... let me know what is still needed and close out the others. Thanks for all the improvements, I will need to put this on a project of mine again soon.

**Comment by danmayer** [comment]
@kbaum let me know if you need help with anything... Also do you have a twitter account?

**Comment by kbaum** [comment]
No problem! Thanks for starting this project. Love the idea! Sorry for too
many prs but I was trying to break them up into small batches and then one
seemed to depend on the other.

My twitter account is kbaum8.

**Comment by danmayer** [comment]
yeah hard to have a bunch of small PRs when they build on each other. Thanks following you now

**Pull request merged**
