### PR TITLE
Adds report-only CSP

### PR DESCRIPTION
**Pull request by jwg2s**
We had numerous issues getting the Coverband web UI to work with our existing CSP rules. This isn't perfect but is an example of how you could fold it into the existing web.rb file.

Feel free to close this and replace with something where you could change it from `Content-Security-Policy-Report-Only` to `Content-Security-Policy` instead.

### CODE REVIEW

**Comment by jwg2s** [comment]
If you give some guidance, I'm happy to fix the formatting issues and push up an additional commit to reach a CSP you'd be comfortable merging.

**Comment by danmayer** [comment]
No worries on the formatting, I believe we have a checked in standardrb config, so if you run `standardrb --fix` it should match the existing style... If that doesn't work for you I can fix up formatting after the PR is good to go and merged.

I think since this hasn't been an issue for most folks and many projects it would be good to make it optional could we have a configurable option off by default. `Coverband.configuration.csp` then if true we add in the headers? Would that work for your needs? @jwg2s

**Comment by danmayer** [comment]
hey folks sorry for the delay on this got a bit lost in my queue and we had an alternative solution in our apps so I hadn't needed anything like this... Anyways, I saw other were pulling this in forks so I cleaned it up on another branch and got a configuration option and it is merged into main... you can give it a go with

`5.2.6.rc.3` to enable CSP add this to your coverband config file

`config.csp_policy = true`

**Comment by danmayer** [comment]
let me know if this works @jwg2s or @scruti

**Comment by danmayer** [comment]
full details on the code change https://github.com/danmayer/coverband/pull/470

**Pull request closed without merging**
