### PR TITLE
Change background reporting frequency

### PR DESCRIPTION
**Pull request by kbaum**

### CODE REVIEW

**Comment by kbaum** [comment]
Did some more experimentation on this on the morning commute. Noticing that `test/unit/rails_full_stack_test.rb` was failing every 10th time. By including as a reload_file, was able to execute 50+ times in a row with no failure.  My theory is that in some cases, the dummy_controller was being required before the `Coverage.start` which causes class load coverage to be missed.

Also added safe_reload_files to reset method in Configuration.

**Comment by danmayer** [comment]
Nice well done @kbaum thanks for digging in

**Comment by kbaum** [comment]
Looks like there are still some failures now. Will dig in some more later on.

**Comment by kbaum** [comment]
Closing as this is my new theory:
https://github.com/danmayer/coverband/pull/194

**Pull request closed without merging**
