### PR TITLE
Improve View tracker to track render collection too

### PR DESCRIPTION
**Pull request by stoivo**
Coverband should track render template, partial and collection, each of these would push message `render_template.action_view`, `render_partial.action_view`, `render_collection.action_view`

### CODE REVIEW

**Review by danmayer — APPROVED** [review]

**Comment by danmayer** [comment]
@stoivo this is in gem 'coverband', '= 5.2.0.rc.1' if you want to help test the RC

**Comment by stoivo** [comment]
There is anouther issue, i dont have the view tracker tab at all. I will try to figure out why

**Comment by stoivo** [comment]
bisect it down to 11ec00d344d64ec624e21a9df9bd71efd4f1017e

**Comment by stoivo** [comment]
Turns out I didn't set COVERBAND_ENABLE_DEV_MODE to true, should I need to set it? Add a comment to readme

**Comment by danmayer** [comment]
hmmm no you shouldn't let me take a closer look at that commit thanks @stoivo

**Comment by danmayer** [comment]
cool so this bug only impacted development, not production, but still awesome to find and fix it in the RC release... There is a new release 'coverband', '= 5.2.0.rc.2' if you want to give that a shot @stoivo and thanks so much

**Comment by stoivo** [comment]
Now, its working in development and staging.

**Comment by stoivo** [comment]
We have deploy it and it works perfectly. Thankgs for merging and maintaining coverband ❤️

**Pull request merged**
