### PR TITLE
Remove classifier reborne from benchmarks

### PR DESCRIPTION
**Pull request by kbaum**
Not sure this is useful anymore

### CODE REVIEW

**Comment by danmayer** [comment]
nice I have been meaning to get rid of this, if you can fix the tests, I am +1 for moving away from that testing method

**Comment by kbaum** [comment]
Sounds good. Build problems seem to be related to bundler:

```
$ echo 'this is a hack to clear default bundler and force bundler 1.17.3'
before_install.2
0.00s$ ls /home/travis/.rvm/gems/
before_install.3
0.00s$ rm /home/travis/.rvm/gems/ruby-2.3.7@global/specifications/bundler-2.0.1.gemspec || true
before_install.4
0.00s$ rm /home/travis/.rvm/gems/ruby-2.4.6@global/specifications/bundler-2.0.1.gemspec || true
before_install.5
0.00s$ rm /home/travis/.rvm/gems/ruby-2.5.5@global/specifications/bundler-2.0.1.gemspec || true
before_install.6
0.21s$ gem uninstall bundler || true
before_install.7
0.62s$ gem install bundler -v '1.17.3'
0.07s$ bundler --version
/home/travis/.rvm/rubies/ruby-2.4.6/lib/ruby/site_ruby/2.4.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
	from /home/travis/.rvm/rubies/ruby-2.4.6/lib/ruby/site_ruby/2.4.0/rubygems.rb:302:in `activate_bin_path'
	from /home/travis/.rvm/gems/ruby-2.4.6/bin/bundler:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'
The command "bundler --version" failed and exited with 1 during .
```

I honestly forget why we did this and not as familiar with the fix.

**Comment by kbaum** [comment]
Sounds good. Build problems seem to be related to bundler:

```
$ echo 'this is a hack to clear default bundler and force bundler 1.17.3'
before_install.2
0.00s$ ls /home/travis/.rvm/gems/
before_install.3
0.00s$ rm /home/travis/.rvm/gems/ruby-2.3.7@global/specifications/bundler-2.0.1.gemspec || true
before_install.4
0.00s$ rm /home/travis/.rvm/gems/ruby-2.4.6@global/specifications/bundler-2.0.1.gemspec || true
before_install.5
0.00s$ rm /home/travis/.rvm/gems/ruby-2.5.5@global/specifications/bundler-2.0.1.gemspec || true
before_install.6
0.21s$ gem uninstall bundler || true
before_install.7
0.62s$ gem install bundler -v '1.17.3'
0.07s$ bundler --version
/home/travis/.rvm/rubies/ruby-2.4.6/lib/ruby/site_ruby/2.4.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
	from /home/travis/.rvm/rubies/ruby-2.4.6/lib/ruby/site_ruby/2.4.0/rubygems.rb:302:in `activate_bin_path'
	from /home/travis/.rvm/gems/ruby-2.4.6/bin/bundler:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'
The command "bundler --version" failed and exited with 1 during .
```

I honestly forget why we did this and not as familiar with the fix.

**Comment by kbaum** [comment]
@danmayer was able to remove the custom travis bundler setup and tests passed.

**Comment by danmayer** [comment]
excellent, the bundler hack was related to an issue for a while about having both Bundler 2.x and 1.7.x on travis... looks like travis fixed that issue.

**Pull request merged**
